{{- if not .Values.config.serverPasswordExistingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moria.passwordSecretName" .}}
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  serverPassword: {{ .Values.config.serverPassword | default (randAlphaNum 10) | quote }}
{{- end }}