apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  spec:
  type: {{ .Values.service.type }}
  selector:
    app: "{{ .Chart.Name }}"
  ports:
  - name: game-port
    port: {{ .Values.config.listenPort | int }}
    targetPort: game-port
    protocol: UDP
