services:
  moria:
    container_name: moria
    image: ghcr.io/bubylou/moria:latest
    restart: unless-stopped
    environment:
      - UPDATE_ON_START=true
      - LISTEN_PORT=7777
      - SERVER_NAME=myserver
      - SERVER_PASSWORD=mypassword
    ports:
      - 7777:7777/udp
    volumes:
      - moria-app:/app/moria # game server files
volumes:
  moria-app:
